version: '2'
services:
  pp:
    container_name: ppap_python
    image: python:3.5.2-alpine
    volumes:
      - ./app/:/mnt/
    working_dir: /mnt
    environment:
      - FLASK_APP=main.py
    expose:
      - 5000
    tty: true
    command: ash -c 'pip install Flask && python -m flask run --host=0.0.0.0'

  a:
    container_name: ppap_apache
    image: httpd:2.4.23-alpine
    volumes:
      - ./httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./htdocs/:/usr/local/apache2/htdocs/
    links:
      - pp
    ports:
      - 80:80

  p:
    container_name: ppap_postgre
    image: postgres:9.6.1-alpine
